### ISSUE TITLE
[RFC] 메인 레이아웃 디자인 

### ISSUE THREAD

**Issue by dev-hamster** [linkarchive/Front-End#105]
## 🙋‍♂️ Suggest

현재 `MainLayout` 컴포넌트가 유연하지 않아 같은 라우트를 공유하는 페이지에서 레이아웃을 변경하기 쉽지 않아보입니다

```javascript
// MainLayout.tsx
    <>
      <WaterMark />
      {!main && <Header />}
      {main && (
        <>
          {home && <HomeHeader />}
          {Archive && <ArchiveHeader />}
          {settings && <SettingsHeader />}
        </>
      )}
      <Main>{children}</Main>
      <BottomNav />
    </>
```

## ❗ When to follow this process
두 페이지 모두 `/[nickname]`으로 라우팅이 될 예정인데 
사용자별 둘러보기 페이지에는 `HomeHeader` 가 노출되지 않아야 합니다

<img width="200" alt="스크린샷 2023-05-29 오후 5 31 41" src="https://github.com/linkarchive/Front-End/assets/123740296/684499da-6e24-41f4-ae49-4f550b1cd241">
<img width="200" alt="스크린샷 2023-05-29 오후 5 32 01" src="https://github.com/linkarchive/Front-End/assets/123740296/c12312f8-a1c8-4d02-9608-12ba3fe988d8">

## As-is

현재 라우트에 따라 레이아웃이 적용됩니다
```javascript
// MainLayout.tsx
    <>
      <WaterMark />
      {!main && <Header />}
      {main && (
        <>
          {home && <HomeHeader />}
          {Archive && <ArchiveHeader />}
          {settings && <SettingsHeader />}
        </>
      )}
      <Main>{children}</Main>
      <BottomNav />
    </>
```

## To-be

`HomeHeader` 컴포넌트를 `/[nickname]`페이지에서 분기처리 하는건 어떨까용?

```javascript
// MainLayout.tsx
    <>
      <WaterMark />
      {!main && <Header />}
      {main && (
        <>
          {Archive && <ArchiveHeader />}
          {settings && <SettingsHeader />}
        </>
      )}
      <Main>{children}</Main>
      <BottomNav />
    </>

// [nickname]
return (
   // ...
   {isUser ? <HomeHeader/> : <Nav/> }
   // ...
)
```

또는 현재 사용자 페이지 라우트는 루트로 분리하는건 어떨까요?

## 👏 What to expect

개인적으로 현재 사용자 페이지 라우트는 루트로 분리하는쪽이 선호가 됩니다

현재 사용자만 볼 수 있는 페이지는 루트로 분리하고
모든 사용자가 볼 수 있는 페이지는 `/[nickname]`로 하는건 어떤가용?

**Comment by 1yoouoo** [comment]
음 ...... 같은 사용자의 페이지 일지라도 

권한이 있는사람, 권한이 없는사람은 페이지를 다르게 보여주자는 건가요?

정확하게 문제를 인지 못했어요 ㅜㅜ

**Comment by dev-hamster** [comment]
넹넹 깃헙은 이렇게 구분되어있어여  
본인 깃헙 페이지 https://github.com/
유저별 깃헙 페이지 https://github.com/dev-hamster 

저희도 마찬가지로 구분하면 어떨까여?
본인 보관함 /
유저별 보관함 /[nickname]

**Comment by dev-hamster** [comment]
본인 보관함, 유저별 보관함 모두 /[nickname]으로 라우트가 잡혀있는데
컴포넌트가 각각 달라야 해여 

저는 두가지 방법이 있다고 생각하는데 
- `MainLayout` 수정
- 라우트 분리

그 중 라우트 분리를 제안해봅니다🤓

**Comment by 1yoouoo** [comment]
아 동의해요 !!
