### ISSUE TITLE
dev환경 /create페이지에서 불러오기가 안되는 이슈

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#124]
## 📌 Feature Issues

<img width="300" alt="Screenshot 2023-06-07 at 6 49 34 PM" src="https://github.com/linkarchive/Front-End/assets/79697414/dec5ffd8-8196-4057-b6f9-d8515a3e96b8">

불러오기기 이후 불러오지 않았는데 추가하기가 활성화 되네요

useQuery -> useMutation으로 수정하는 과정에서 생기는 에러일까요?
테스트 환경에서는 잘 동작했었는데 말이에요

**Comment by dev-hamster** [comment]
https://github.com/linkarchive/Front-End/pull/129

프로퍼티를 잘못 접근하였습니다 ^^;
