### ISSUE TITLE
width 360 이하인 경우 반응형 레이아웃 깨짐

### ISSUE THREAD

**Issue by dev-hamster** [linkarchive/Front-End#128]
## 📌 Feature Issues

- width 360 이하인 경우 레이아웃이 깨집니다
- 팝업창 z-index 수정이 필요

## ✨ To-do

<img width="406" alt="스크린샷 2023-06-08 오후 3 30 19" src="https://github.com/linkarchive/Front-End/assets/123740296/b58f5676-e5ef-456f-8320-6ace758563c5">

**Comment by 1yoouoo** [comment]
https://github.com/linkarchive/Front-End/assets/79697414/2f9e690b-fb7c-4bce-9d19-13b5a22ab3f3

헛헛.. 이게 왜 안깨지죠? 어느 상황에서 저 버그가 나타나는 걸까요?

**Comment by dev-hamster** [comment]
모바일 디바이스로 선택하고 이렇게 설정하면 디자인이 꺠집니다 ㅠ_ㅠ 
<img width="409" alt="스크린샷 2023-06-19 오전 10 48 11" src="https://github.com/linkarchive/Front-End/assets/123740296/fdec041a-8141-42cf-aa15-204f34a59022">
