### ISSUE TITLE
프로필 조회 이미지 최적화

### ISSUE THREAD

**Issue by dev-hamster** [linkarchive/Front-End#135]
## 📌 Feature Issues

`/nickname` 링크, 마크 첫 렌더링시 프로필 이미지 안보임

![image](https://github.com/linkarchive/Front-End/assets/123740296/ae303571-85c1-45bb-bdff-d54b47c7f04a)

## ✨ To-do
- [x] 레이아웃으로 나누기
- [x] _app.tsx -> per-page layout으로 받기위해 코드 수정
- https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts
- [x] ProfileLayout 컴포넌트 생성

**Comment by 1yoouoo** [comment]
이 부분은 확인이 안되는데 어떤 상황에서 발생하시나여?

너무 늦게 나오는 상황을 말씀하시는 건가여?

**Comment by dev-hamster** [comment]
맞아여 프로필이 늦게 뜨네여 ㅠ 링크 → 마크 로 최초 이동시에 발생해여
마크로 이동했을 때 프로필 api가 한번 더 패치되네여 😓
