### ISSUE TITLE
로그인 후 둘러보기로 이동

### ISSUE THREAD

**Issue by dev-hamster** [linkarchive/Front-End#140]
## 📌 Feature Issues
서비스 컨셉에 맞춰 로그인 완료 후 홈이 아닌 `/archive` 변경

## ✨ To-do
- [ ]

**Comment by 1yoouoo** [comment]
@dev-hamster 
이 부분 home으로 이동하는 게 더 적절하지 않나요?

어떤 부분에서 둘러보기로 이동하는게 좋다고 판단하셨나요?

**Comment by dev-hamster** [comment]
오... 뭐였더라,..,.? 그 때 얘기나온 것들 급하게 정리하느라 설명이 빠졋네요 ㅋㅋㅋㅋ
오늘 회의 안건으로 넘깁시다
