### ISSUE TITLE
useAuth 제거

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#157]
## 📌 Feature Issues
useAuth의 기능은 로그인 한 상태를 받아오는데

getAccessToken으로 충분히 가져올 수 있을 거라 판단해서 제거해도 될 거 같아요

## ✨ To-do
- [ ] useAuth 제거
- [ ] isLoggedIn 업데이트

**Comment by dev-hamster** [comment]
오 `useAuth` 훅은 레이어를 나누면 좋을 것 같애서 만들었어여 
상위 컴포넌트에서 로그인 여부 상태값을 확인하기 위해서는 `@/api/customAPI` 보다 `@/hooks/useAuth`에서 가져오는게 더 안잔하다고 생각되어여! 저수준에 있는 도메인의 값을 쓰기 보다는 중간 단계에 있는 도메인의 값을 사용하는게 향후 유지보수에도 좋을 것 같구요~

**Comment by 1yoouoo** [comment]
> 오 `useAuth` 훅은 레이어를 나누면 좋을 것 같애서 만들었어여 상위 컴포넌트에서 로그인 여부 상태값을 확인하기 위해서는 `@/api/customAPI` 보다 `@/hooks/useAuth`에서 가져오는게 더 안잔하다고 생각되어여! 저수준에 있는 도메인의 값을 쓰기 보다는 중간 단계에 있는 도메인의 값을 사용하는게 향후 유지보수에도 좋을 것 같구요~

그렇군요 setIsLoggedIn이 사용되지 않아서 생각을 깊게하지 않았네요

진아님 말씀에 동의해요. 혹시 setIsloggedIn은 어떻게 사용될 예정인가요?

**Comment by dev-hamster** [comment]
헉 현재로선 `setIsLoggedIn` 사용방도가 없네요 권한 처리를 항상 클라쪽에서 처리해와서 습관적으로 만들었습니다 ^^;

**Comment by 1yoouoo** [comment]
그렇군여 앞으로 서비스 어떻게 진행되냐에 따라서 좀 더 고민해볼게요~!
