### ISSUE TITLE
[RFC] 토스트 바 리팩토링 제안

### ISSUE THREAD

**Issue by dev-hamster** [linkarchive/Front-End#208]
## 🙋‍♂️ Suggest
토스트 메세지 개선을 하고싶습니다

## ❗ When to follow this process
토스트 메세지를 호출할 때 `dispatch`를 직접 호출해야하는데
`useToastBar` 훅을 만들어 사용하면 더 좋을 것 같습니다

## As-is
```javascript
// pages/create/index.tsx

  createLink.mutate(
    { url, title, description, thumbnail, tags },
    {
      onSuccess: () => {
        dispatch(createToastBar({ text: '링크가 추가되었습니다.' }));
        // ...
      },
    }
  );
```

## To-be
어떻게 해야할지 조사중입니다...

## 👏 What to expect
훅으로 분리해서 페이지 단에서 `redux`를 직접 호출하는 것을 개선할 수 있습니다

**Comment by 1yoouoo** [comment]
좋습니다.

'토스트 메세지가 필요한 페이지 -> 훅 실행 -> dispatch 호출'이 되는걸까요?
