### ISSUE TITLE
Header 포지션 relative

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#224]
현재 header 포지션이 relative여서 아래에 위치하는 박스들을 밀어내고 있어요

하지만 로그인 화면에서 배경색을 주면 전체색이 덮어지지 않아요

그렇다고 absolute로 잡으면 모든 페이지에서 padding으로 밀어내는 코드를 추가해야해요 어쩌지요~?

<img width="381" alt="Screenshot 2023-08-04 at 1 39 59 PM" src="https://github.com/linkarchive/Front-End/assets/79697414/285c07bc-e285-4938-b4f6-33f4d26ee135">

**Comment by dev-hamster** [comment]
https://github.com/linkarchive/Front-End/pull/236#discussion_r1285249327

`MainLayout`을 안타도록 만들었는데 요건 어떤가여?

**Comment by dev-hamster** [comment]
흐음 어째서 아예 뺼수가 없나여 ㅠㅠ?

**Comment by 1yoouoo** [comment]
뺄 순 있는데 피그마에서는 존재해서 뺄 수 없네요 ㄷㄷ

<img width="216" alt="Screenshot 2023-08-10 at 10 45 10 AM" src="https://github.com/linkarchive/Front-End/assets/79697414/967ce241-00a5-4e9a-86cd-0e30c8b92949">

**Comment by dev-hamster** [comment]
https://github.com/linkarchive/Front-End/pull/244 
해결된건가용??

**Comment by 1yoouoo** [comment]
> 

네

**Comment by dev-hamster** [comment]
오!! close 하겠습니다
