### ISSUE TITLE
자주 사용하는 태그 추가 후 즉각 반영

### ISSUE THREAD

**Issue by dev-hamster** [linkarchive/Front-End#271]
## 📌 Feature Issues
자주 사용하는 태그 추가 후 즉각 반영이 되지 않습니다
새로고침 후에 반영이 됩니다

https://github.com/linkarchive/Front-End/assets/123740296/763db3d0-6007-418d-9f31-5d52a0e2c9c6

## ✨ To-do
- [ ]

**Comment by dev-hamster** [comment]
리액트 쿼리 문제로 보입니다
https://github.com/linkarchive/Front-End/issues/269 이 이슈와 함께 처리할 수 있을 것 같습니다

**Comment by dev-hamster** [comment]
피그마 디자인 반영은 다른 이슈에서 처리하는게 좋을 것 같아여

**Comment by 1yoouoo** [comment]
> 피그마 디자인 반영은 다른 이슈에서 처리하는게 좋을 것 같아여

넵!
