### ISSUE TITLE
api서버 호출 시 status에 관한 이슈

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#67]
react-query를 사용하던 도중 onSuccess, onError에 사용에 대해 궁금함이 생김

onSuccess => status 200일 경우 호출
onError => 그 외 status일 경우 호출

현재 서버에서 api호출 시 '잘못된 인증코드', '비밀번호 오류'등 status 200으로 넘겨주고 있어요.

이 부분도 어떻게 보면 에러인데 react-query에서는 onSuccess로 호출이 돼요

어떤 부분을 에러라고 생각해야할지, 어느 부분까지 에러라고 봐야할 지 고민이 되네요

400, 401, 404, 500 등 이 부분만 에러라고 봐야할 지 

아니면 로그인 실패, 인증 실패등도 에러로 넘겨줘야할 지

명확하게 구분짓기가 어렵네요!

**Comment by dev-hamster** [comment]
'잘못된 인증코드', '비밀번호 오류' 등에 해당하는 상태코드를 정녕 변경할 수 없는 건가요 ㅠㅠ?

변경할 수 없다면 해당 케이스들은 onSucess에서 적절하게 처리할수밖에 없을것 같습니다 … 현재 로그인을 확인해보지 않았습니다만 해당하는 케이스들은 alert으로 매새지 띄우고 로그인 페이지로 이동하면 어떨까용? 🥺

**Comment by 1yoouoo** [comment]
아 처리할 수 있어요 태균님이랑 같이 테스트 해봤는데 가능해요..!
다만 하다보니까 태균님은 이렇게 바꾸는게 맞는거 같다라고 보셨는데

먼저 의견을 낸 제가 다시생각해보니까 과연 이게 에러가 맞나 생각이 들어서요

오히려 처음 코드가 맞을지도 모르겠다라는 생각이 들어서 진아님한테 의견 물어봤어요

**Comment by dev-hamster** [comment]
아하 저는 심풀하게 접근하면 좋을 것 같아요! 200은 http 성공 상태이므로 로그인 성공인 상태로만 받아들이고 그 외의 케이스는 에러로 넘기면 어떨까싶습니다🤓

**Comment by 1yoouoo** [comment]
http 관련 상태를 기준으로 잡는다면 비밀번호가 틀린경우도 http성공으로도 볼수 있는거 아닐까요!?

**Comment by dev-hamster** [comment]
비밀번호가 틀린경우라하면은 음~ 400에 해당하지 않을까요? Http 통신자체는 성공햇으나 비밀번호가 틀렸기때문에 서버는 에러라고 판단하지 안을까용??https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400

**Comment by 1yoouoo** [comment]
아 문서보니까 알 거 같아요 오늘 다른 페이지 참고 하면서 생각정리해서 남겨드릴게요 감사해용

**Comment by dev-hamster** [comment]
넵 !!! 빠이팅입니다💪
