### ISSUE TITLE
[RFC] 토큰을 저장할 저장소에 대한 제안

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#73]
## 🙋‍♂️ Suggest

Next.js의 페이지 권한 확인에 대한 일반적인 두 가지 방법이 있어요
1. 서버 사이드 렌더링
2. 미들웨어

1번을 사용하면 클라이언트 상황에 따라 동적으로 처리할 수 있는 장점이있는 반면에
모든 페이지에 서버사이드렌더링 처리를 해야하는 단점이있어요

2번을 사용하면 모든 요청에 대해서 요청이 처리되기 전 실행되는 방법이라 코드를 반복적으로 작성하지 않아도 된다는 장점이 있어요

미들웨어로 사용하는 방법이 둘러보기를 제외한 모든 페이지에 권한을 확인하는 우리 어플리케이션에 적합하다고 생각이돼요.

## ❗ When to follow this process

로컬 스토리지에 토큰을 저장하면 서버사이드렌더링으로 권한확인을 선택할 수 밖에 없는데 모든 페이지에 서버사이드 렌더링에 대한 로직을 작성해야해서 반복되는 코드가 생겨요

## As-is
토큰을 발급받으면 로컬스토리지에 저장해요

## To-be
토큰을 발급받으면 쿠키에 저장해요

## 👏 What to expect
쿠키에 저장해서 미들웨어를 통해 페이지 권한을 확인하게 된다면 모든 요청에 미들웨어가 실행돼서 1번의 코드로 모든 권한을 확인 할 수 있게 돼요

쿠키에 토큰을 저장하려고 하는데 @dev-hamster 진아님은 어떻게 생각하시나요?

**Comment by dev-hamster** [comment]
오 Next가 지원하는 미들웨어를 사용해서 권한이 없으면 로그인 페이지로 튕기자는 전략으로 이해했는데 맞나요?
좋아요 쿠키로 토큰 관리합시다 👍

(질문) 클라이언트 사이드에서도 권한 확인할 수 있지 안나요?_?

**Comment by dev-hamster** [comment]
미들웨어 사용/미사용 두 케이스 다 매력적이네여~ (주저리입니다 ㅎㅎ)

로그인한 사용자가 /링크보관함 접근:
미들웨어 궈한 확인(서버) -> 링크 보관함 api 패치(클라) -> 랜더링 
미들웨어로 라우팅을 납치해가니 보안에서 강점이 있네요!

미들웨어 사용 x
로그인 확인(클라) ->  링크보관함 api 패치(클라) -> 렌더링 
미들웨어를 사용하지 안으면 fcp에서 이점을 받을 것 같구요~
