### ISSUE TITLE
getServerSideProps에 권한을 확인하는 방법에 대한 고찰

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#82]
서버사이드 렌더링에 권한을 포함하는게 보안적으로 안전한 지에 대해 고민

혹은 그러한 방법이 권장되는지 찾아봐야함

**Comment by 1yoouoo** [comment]
관련 링크있으면 첨부부탁드려요~!!

**Comment by dev-hamster** [comment]
넵 알겠습니다 관련 자료 확인하고 공유하겟습니다!!
