### ISSUE TITLE
getUserProfile api함수 분리 (my, user)

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#85]
현재 두 페이지에서 같은 api를 사용하고있는데 서로 다른 성격의 페이지라고 판단해서 분리를 했습니다.

분리한 이유:
1. 비로그인 유저는 (2번 이미지) 다른 사람의 프로필을 볼 수 있음
2. 로그인 유저는 자기 프로필(1번 이미지)을 볼 수 없음(프로필이 없으니)
3. 1번 이미지와 2번 이미지의 페이지는 각각 서로 다른 성격이라고 생각함

1번 이미지:
<img width="200" alt="Screenshot 2023-05-23 at 3 51 23 PM" src="https://github.com/linkarchive/Front-End/assets/79697414/533f3756-c6aa-43e3-8193-8cf5d3a620f8">
2번 이미지:
<img width="200" alt="Screenshot 2023-05-23 at 3 51 30 PM" src="https://github.com/linkarchive/Front-End/assets/79697414/5e766ebd-ce48-490c-b4b6-275b5b9af9be">

**Comment by dev-hamster** [comment]
넵 좋아요 저도 동의합니다~
