### ISSUE TITLE
쿠키 저장 후 즉시 값을 사용할 수 없는 버그

### ISSUE THREAD

**Issue by 1yoouoo** [linkarchive/Front-End#87]
소셜 로그인 후 쿠키를 저장고 Application탭에도 보이지만

실제로 값을 가져다가 쓰려면 새로고침이 1회 필요해요

router.push('/')를 이용하면 쿠키의 값을 바로 가져다가 쓸 수 없네요

**Comment by 1yoouoo** [comment]
새로고침없이 사용하려면 state로 관리해야하는데 이 방법은 좋은 방법은 아닌거 같고

login -> auth/kakao -> home

이런 로직인데

login -> auth/kakao -> refresh용 페이지 -> home 이렇게 새로고침을 한번 시키고 홈으로 보내는 방법은 어떠신가요?

**Comment by dev-hamster** [comment]
흠 저는 redux로 관리해도 좋다고 생각해요!
새로고침없이 상태관리를 하면 SPA 장점을 살릴 수 있다고 생각해요~~

**Comment by 1yoouoo** [comment]
> 흠 저는 redux로 관리해도 좋다고 생각해요! 새로고침없이 상태관리를 하면 SPA 장점을 살릴 수 있다고 생각해요~~

redux로 관리해본 경험이 없는데 괜찮은 방법인 거 같아요.

현재 서버사이드렌더링이 필요한 페이지는 권한을 뺏기 때문에 가능해보여요

다만 페이지 전환이 됐을 때 state를 날리지 않는 방법이 있다고 하셨는데 어떤 링크를 참고하면 될까요?

**Comment by dev-hamster** [comment]
넵!! 제가 생각한 부분 말씀드리겟습니다!!!

login → auth/kakao (토큰 발급) →  home 

토큰을 발급받는 시점에 쿠키와 `redux` 에 토큰 값을 저장합니다

페이지 이동:
`redux` 의 상태값이 정상적으로 유지됩니다
로그인 후 home으로 이동하여도 토큰값이 유지된다고 예상됩니다! 

페이지 새로고침:
`redux-persis` 라이브러리를 사용하여 새로고침시에도 토큰값을 유지합니다
https://www.npmjs.com/package/redux-persist
[redux-persist-cookie-storage](https://github.com/abersager/redux-persist-cookie-storage)

이렇게 관리하게 된다면 로그인 후 새로고침을 하지 않고도 토큰값을 유지할 수 있다고 생각해요~~

**Comment by 1yoouoo** [comment]
redux-persist를 이용해서 구현해보도록 할게요~~!
